[build]
  base = ""
  command = "node ./build.js"
  publish = "public"

[[redirects]]
  from = "https://6532690cd2a147103d15aff0--starlit-kangaroo-2a48c7.netlify.app/"
  to = "http://localhost:3000"
  status = 301 
